In [1]:
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from keras.models import Sequential
from keras.layers import Activation
from keras.optimizers import SGD
from keras.layers import Dense
from keras.utils import np_utils
from imutils import paths
import numpy as np
import cv2
import os

Using TensorFlow backend.


In [21]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


# Hide warnings
import warnings
warnings.filterwarnings('ignore')

In [66]:
newwa = r'C:/Users/HP/Downloads/dogs-vs-cats/train/train/cat.'
  


In [67]:
def image_to_feature_vector(image, size=(32, 32)):
	# resize the image to a fixed size, then flatten the image into
	# a list of raw pixel intensities
	return cv2.resize(image, size).flatten()

In [69]:
data=[]
rl=[]
labels=[]
for i in range(12500):
    henc=newwa+str(i)+'.jpg'
    imgr=cv2.imread(henc)
    labels.append('cat')
    new_data=image_to_feature_vector(imgr)
    data.append(new_data)
   
   
    
    

In [78]:
data[300]


array([ 83, 109, 135, ...,  26,  34,  51], dtype=uint8)

In [79]:
labels[300]

'cat'

In [80]:
neww = r'C:/Users/HP/Downloads/dogs-vs-cats/train/train/dog.'

In [81]:
for i in range(12500):
    hen=neww+str(i)+'.jpg'
    imr=cv2.imread(hen)
    labels.append('dog')
    new_dat=image_to_feature_vector(imr)
    data.append(new_dat)

In [82]:
data[20000]

array([ 90,  92,  86, ..., 249, 246, 254], dtype=uint8)

In [83]:
labels[20000]

'dog'

In [84]:
le = LabelEncoder()
labels = le.fit_transform(labels)
# scale the input image pixels to the range [0, 1], then transform
# the labels into vectors in the range [0, num_classes] -- this
# generates a vector for each label where the index of the label
# is set to `1` and all other entries to `0`
data = np.array(data) / 255.0
labels = np_utils.to_categorical(labels, 2)

In [88]:
labels[200]

array([1., 0.], dtype=float32)

In [89]:
model = Sequential()
model.add(Dense(768, input_dim=3072, init="uniform",
	activation="relu"))
model.add(Dense(384, activation="relu", kernel_initializer="uniform"))
model.add(Dense(2))
model.add(Activation("softmax"))

In [90]:
sgd = SGD(lr=0.01)
model.compile(loss="binary_crossentropy", optimizer=sgd,
	metrics=["accuracy"])
model.fit(data, labels, epochs=50, batch_size=128,
	verbose=1)

Epoch 1/50
25000/25000 [==============================] - 14s 549us/step - loss: 0.6821 - accuracy: 0.5626
Epoch 2/50
25000/25000 [==============================] - 9s 352us/step - loss: 0.6607 - accuracy: 0.5992
Epoch 3/50
25000/25000 [==============================] - 10s 381us/step - loss: 0.6510 - accuracy: 0.6183
Epoch 4/50
25000/25000 [==============================] - 9s 378us/step - loss: 0.6433 - accuracy: 0.6280
Epoch 5/50
25000/25000 [==============================] - 10s 397us/step - loss: 0.6372 - accuracy: 0.6327
Epoch 6/50
25000/25000 [==============================] - 10s 398us/step - loss: 0.6337 - accuracy: 0.6412
Epoch 7/50
25000/25000 [==============================] - 9s 360us/step - loss: 0.6299 - accuracy: 0.6435
Epoch 8/50
25000/25000 [==============================] - 10s 385us/step - loss: 0.6218 - accuracy: 0.6526
Epoch 9/50
25000/25000 [==============================] - 10s 385us/step - loss: 0.6191 - accuracy: 0.6551
Epoch 10/50
25000/25000 [===============

In [115]:
testpd=r'C:/Users/HP/Downloads/dogs-vs-cats/test1/test1/'

In [165]:
testpi=20
newtestdp=testpd+str(testpi)+'.jpg'

In [166]:
newtestdp

'C:/Users/HP/Downloads/dogs-vs-cats/test1/test1/20.jpg'

In [167]:
testcvp=cv2.imread(newtestdp)
features = image_to_feature_vector(testcvp) / 255.0
features = np.array([features])


In [168]:
probs = model.predict(features)[0]
prediction = probs.argmax(axis=0)

In [169]:
if prediction==0:
    print('cat')
else:
    print('dog')

cat
